resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:1e298ca3a59920bfcd110893027433292c5b569540841e3f3d5c3cf893822f30
  name: controller
  newName: ghcr.io/open-digital-twin/ktwin-operator
