resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:bee2a4e402073eb04f43245a3c54a88b45c094cb6a461b3501bcd2e334421249
  name: controller
  newName: ghcr.io/open-digital-twin/ktwin-operator
