resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:f077ac87df6cab02cac22efbb14d91b720c0fabf94d87ca7d0fdd9b204a21c75
  name: controller
  newName: ghcr.io/open-digital-twin/ktwin-operator
