resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:d3a86123394cef212785d8785888a85a6c7eddfca42605c75a2c9e1b32087d3d
  name: controller
  newName: ghcr.io/open-digital-twin/ktwin-operator
