resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:2c6edbf47ef43ba79c48cfeb5c5f6c79055ab1df873b56cb07b33ce316f55e16
  name: controller
  newName: ghcr.io/open-digital-twin/ktwin-operator
