resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:290e20b9f0fbc84404566a23a3be2880b5f8a20051673551312d0e3b25dee8f1
  name: controller
  newName: ghcr.io/open-digital-twin/ktwin-operator
