---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: controller
    release: prometheus
  name: controller
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
    - ktwin
  selector:
    matchLabels:
      app: controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: autoscaler
    release: prometheus
  name: autoscaler
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
    - ktwin
  selector:
    matchLabels:
      app: autoscaler
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: activator
    release: prometheus
  name: activator
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-serving
    - ktwin
  selector:
    matchLabels:
      app: activator
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: webhook
    release: prometheus
  name: webhook
  namespace: knative-serving
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: metrics
  namespaceSelector:
    matchNames:
    - knative-serving
    - ktwin
  selector:
    matchLabels:
      app: webhook
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: broker-filter
    release: prometheus
  name: broker-filter
  namespace: knative-eventing
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-eventing
    - ktwin
  selector:
    matchLabels:
      eventing.knative.dev/brokerRole: filter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: broker-ingress
    release: prometheus
  name: broker-ingress
  namespace: knative-eventing
spec:
  endpoints:
  - honorLabels: true
    interval: 30s
    path: /metrics
    port: http-metrics
  namespaceSelector:
    matchNames:
    - knative-eventing
    - ktwin
  selector:
    matchLabels:
      eventing.knative.dev/brokerRole: ingress
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: eventing-controller
  labels:
    app: eventing-controller
    release: prometheus
  namespace: knative-eventing
spec:
  selector:
    matchLabels:
      app: eventing-controller
  namespaceSelector:
    matchNames:
    - knative-eventing
    - ktwin
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: imc-controller
  namespace: knative-eventing
  labels:
    app: imc-controller
    release: prometheus
spec:
  selector:
    matchLabels:
      messaging.knative.dev/role: controller
  namespaceSelector:
    matchNames:
    - knative-eventing
    - ktwin
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ping-source
  namespace: knative-eventing
  labels:
    app: ping-source
    release: prometheus
spec:
  selector:
    matchLabels:
      eventing.knative.dev/source: ping-source-controller
  namespaceSelector:
    matchNames:
    - knative-eventing
    - ktwin
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: apiserver-source
  namespace: knative-eventing
  labels:
    app: apiserver-source
    release: prometheus
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      eventing.knative.dev/source: apiserver-source-controller
  podMetricsEndpoints:
  - honorLabels: true
    path: /metrics
    port: metrics