apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-kube-prometheus-prometheus
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
rules:
  - verbs: ["get", "list", "watch"]
    apiGroups: [""]
    resources: ["pods", "namespaces", "secrets", "configmaps", "endpoints", "services", "events", "serviceaccounts"]
  - verbs: ["get", "list", "watch"]
    apiGroups: ["extensions"]
    resources: ["ingresses"]
  - verbs: ["get", "list", "watch"]
    apiGroups: ["apps"]
    resources: ["deployments", "deployments/finalizers"]
  - verbs: ["get", "list", "watch"]
    apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
  - verbs: ["get", "list", "watch"]
    apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
  - verbs: ["get", "list", "watch"]
    apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
  - verbs: ["get", "list", "watch"]
    apiGroups: ["serving.knative.dev", "networking.internal.knative.dev", "autoscaling.internal.knative.dev", "caching.internal.knative.dev"]
    resources: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions", "customresourcedefinitions/status"]
    verbs: ["get", "list", "watch"]
  - verbs: ["get", "list", "watch"]
    apiGroups: ["eventing.knative.dev", "messaging.knative.dev", "sources.knative.dev", "flows.knative.dev", "bindings.knative.dev"]
    resources: ["*"]
