# permissions for end users to view gateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gateway-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator-v4
    app.kubernetes.io/part-of: dt-operator-v4
    app.kubernetes.io/managed-by: kustomize
  name: gateway-viewer-role
rules:
- apiGroups:
  - core.ktwin
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.ktwin
  resources:
  - gateways/status
  verbs:
  - get
