# permissions for end users to view twininstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: twininstance-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator-v4
    app.kubernetes.io/part-of: dt-operator-v4
    app.kubernetes.io/managed-by: kustomize
  name: twininstance-viewer-role
rules:
- apiGroups:
  - dtd.ktwin
  resources:
  - twininstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dtd.ktwin
  resources:
  - twininstances/status
  verbs:
  - get
