# permissions for end users to edit twininterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: twininterface-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dt-operator-v4
    app.kubernetes.io/part-of: dt-operator-v4
    app.kubernetes.io/managed-by: kustomize
  name: twininterface-editor-role
rules:
- apiGroups:
  - dtd.ktwin
  resources:
  - twininterfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dtd.ktwin
  resources:
  - twininterfaces/status
  verbs:
  - get
