# permissions for end users to view twininterfaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: twininterface-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ktwin-operator
    app.kubernetes.io/part-of: ktwin-operator
    app.kubernetes.io/managed-by: kustomize
  name: twininterface-viewer-role
rules:
- apiGroups:
  - dtd.ktwin
  resources:
  - twininterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dtd.ktwin
  resources:
  - twininterfaces/status
  verbs:
  - get
