apiVersion: core.ktwin/v0
kind: EventStore
metadata:
  labels:
    app.kubernetes.io/name: event-store
  name: event-store
  namespace: ktwin
spec:
  timeout: 3000
  resources:
    requests:
      memory: "128Mi"
      cpu: "400m"
    limits:
      memory: "256Mi"
      cpu: "800m"
  autoScaling:
    maxScale: 25
    minScale: 3
    target: 20
    parallelism: 200
    targetUtilizationPercentage: 65
    metric: "concurrency"