apiVersion: core.ktwin/v0
kind: EventStore
metadata:
  labels:
    app.kubernetes.io/name: event-store
  name: event-store
  namespace: ktwin
spec:
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  autoScaling:
    maxScale: 25
    minScale: 3
    target: 5
    targetUtilizationPercentage: 65
    parallelism: 100
    metric: "concurrency"