apiVersion: core.ktwin/v0
kind: EventStore
metadata:
  labels:
    app.kubernetes.io/name: event-store
  name: event-store
  namespace: ktwin
spec:
  autoScaling:
    maxScale: 25
    minScale: 3
    target: 10
    parallelism: 1000
    metric: "concurrency"