apiVersion: dtd.ktwin/v0
kind: TwinInterface
metadata:
  labels:
    app.kubernetes.io/name: twininterface
    app.kubernetes.io/instance: twininterface-sample
    app.kubernetes.io/part-of: ktwin-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ktwin-operator
  name: twininterface-sample
spec:
  # TODO(user): Add fields here
